### ISSUE TITLE
publish v1

### ISSUE THREAD

**Issue by simbleau** [loopystudios/bevy_vello#3]
I cannot publish v1 of bevy-vello, since there are unpublished dependencies.

- vello (see https://github.com/linebender/vello/issues/302)
- vellottie (dependent on vello)
- vello_svg (dependent on vello)

**Comment by PoignardAzur** [comment]
FYI: Currently trying to give the whole process a push. Though obviously I can't promise anything.

**Comment by PoignardAzur** [comment]
Quick update: I'm hoping we'll get it done within two weeks. All the major blockers are gone, what remains is small tweaks and administrative stuff to figure out.

**Comment by simbleau** [comment]
> Quick update: I'm hoping we'll get it done within two weeks. All the major blockers are gone, what remains is small tweaks and administrative stuff to figure out.

Thanks, Oliver! No rush.

**Comment by simbleau** [comment]
Fixed
