### ISSUE TITLE
enhancement: Use `SpatialBundle` inside our bundles

### ISSUE THREAD

**Issue by simbleau** [loopystudios/bevy_vello#44]
Currently we have transforms, global transforms, visibility, etc. inlined into each bundle (`VelloSceneBundle`, `VelloAssetBundle`, `VelloTextBundle`).

We should take the approach of [`splined`](https://github.com/cpetzold/splined/blob/8cd8fcf2371b66a3f5e54a89758c594c79884e80/src/spline.rs#L93) and perhaps inline the `SpatialBundle` instead.

**Comment by cpetzold** [comment]
I go back and forth on it -- it's nice to simplify the code but the UX suffers a little bit needing to now nest into `SpatialBundle` for customizing its components.

**Comment by simbleau** [comment]
Wondering if there's a macro to flatten it, like `#[serde(flatten)]`?

**Comment by cpetzold** [comment]
By the way I asked this on the Bevy discord a while ago: https://discord.com/channels/691052431525675048/742569353878437978/1145869833729216583

Looks like the conclusion I came to there is that inlining the components is nice to mirror native bundles like `SpriteBundle`.

**Comment by simbleau** [comment]
Since it appears to be the convention... we'll keep as is. Won't do.
